

data_dir: "path/to/your/data/directory"
results_dir: "path/to/your/results/directory"
clip_model_str: "ViT-B/32"
model_name_str: 'resnet50'
num_epochs: 10
lr: 0.01
batch_size: 32
val_split: 0.8
schedualer_gamma: 0.1
schedualer_step: 1