data_dir: "path/to/your/data/directory"
results_dir: "path/to/your/results/directory"

clip_model_str: "ViT-B/32"
model_name_str: "resnet18"
choose_main: "skimage"

#training parameters
num_features: 512
num_epochs: 7
read_epoch_num: 1
lr: 0.001
batch_size: 32
val_split: 0.9
schedualer_gamma: 0.6
schedualer_step: 1

# skimage descriptions
descriptions:
  {
        "page": "a page of text about segmentation",
        "chelsea": "a facial photo of a tabby cat",
        "astronaut": "a portrait of an astronaut with the American flag",
        "rocket": "a rocket standing on a launchpad",
        "motorcycle_right": "a red motorcycle standing in a garage",
        "camera": "a person looking at a camera on a tripod",
        "horse": "a black-and-white silhouette of a horse",
        "coffee": "a cup of coffee on a saucer"
    }